<?php

putenv('DISPLAY_ERRORS_DETAILS=' . true);

putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_HOST=localhost');
putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_DBNAME=codeeasy_gerenciador_de_lojas');
putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_USER=root');
putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_PASSWORD=root');
putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_PORT=3308');